<a href="https://colab.research.google.com/github/kuir-juach/formative_assignment_PCA/blob/main/Formative_Assignment_PCA_%5Bname_of_student%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [27]:
#import necessary package
#TO DO
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [28]:
#Loading Dataset

fuel_econ = pd.read_csv ("/content/drive/MyDrive/Machine learning folder/fuel_econ.csv")
fuel_econ

id        make             model  year           VClass  \
0     32204      Nissan              GT-R  2013  Subcompact Cars   
1     32205  Volkswagen                CC  2013     Compact Cars   
2     32206  Volkswagen                CC  2013     Compact Cars   
3     32207  Volkswagen        CC 4motion  2013     Compact Cars   
4     32208   Chevrolet    Malibu eAssist  2013     Midsize Cars   
...     ...         ...               ...   ...              ...   
3924  39882      Toyota       Prius Prime  2018     Midsize Cars   
3925  39898     Hyundai     Sonata Hybrid  2018     Midsize Cars   
3926  39899     Hyundai  Sonata Hybrid SE  2018     Midsize Cars   
3927  39900       Lexus            LS 500  2018     Midsize Cars   
3928  39901       Lexus        LS 500 AWD  2018     Midsize Cars   

                  drive                             trans          fuelType  \
0       All-Wheel Drive                   Automatic (AM6)  Premium Gasoline   
1     Front-Wheel Drive                 Automatic (AM-S6)  Premium Gasoline   
2     Front-Wheel Drive                    Automatic (S6)  Premium Gasoline   
3       All-Wheel Drive                    Automatic (S6)  Premium Gasoline   
4     Front-Wheel Drive                    Automatic (S6)  Regular Gasoline   
...                 ...                               ...               ...   
3924  Front-Wheel Drive  Automatic (variable gear ratios)  Regular Gasoline   
3925  Front-Wheel Drive                   Automatic (AM6)  Regular Gasoline   
3926  Front-Wheel Drive                   Automatic (AM6)  Regular Gasoline   
3927   Rear-Wheel Drive                   Automatic (S10)  Premium Gasoline   
3928    All-Wheel Drive                   Automatic (S10)  Premium Gasoline   

      cylinders  displ  pv2  pv4     city    UCity  highway  UHighway  \
0             6    3.8   79    0  16.4596  20.2988  22.5568   30.1798   
1             4    2.0   94    0  21.8706  26.9770  31.0367   42.4936   
2             6    3.6   94    0  17.4935  21.2000  26.5716   35.1000   
3             6    3.6   94    0  16.9415  20.5000  25.2190   33.5000   
4             4    2.4    0   95  24.7726  31.9796  35.5340   51.8816   
...         ...    ...  ...  ...      ...      ...      ...       ...   
3924          4    1.8    0    0  55.2206  78.8197  53.0000   73.6525   
3925          4    2.0    0  106  39.0000  55.9000  44.3066   64.0000   
3926          4    2.0    0  106  40.0000  56.0000  46.0000   64.0000   
3927          6    3.4   99    0  19.2200  24.2000  30.2863   43.4000   
3928          6    3.4   99    0  18.0431  22.6000  27.0000   39.3000   

         comb  co2  feScore  ghgScore  
0     18.7389  471        4         4  
1     25.2227  349        6         6  
2     20.6716  429        5         5  
3     19.8774  446        5         5  
4     28.6813  310        8         8  
...       ...  ...      ...       ...  
3924  54.4329   78       10        10  
3925  41.0000  217        9         9  
3926  42.0000  212        9         9  
3927  23.0021  387        5         5  
3928  21.3945  417        4         4  

[3929 rows x 20 columns]

In [2]:

data = np.array([
    [   1,   2,  -1,   4,  10],
    [   3,  -3,  -3,  12, -15],
    [   2,   1,  -2,   4,   5],
    [   5,   1,  -5,  10,   5],
    [   2,   3,  -3,   5,  12],
    [   4,   0,  -3,  16,   2],
])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

Putting data on the same scale enhances model performance by preventing any feature from dominating the learning process. It also leads to more accurate, interpretable, and faster results.

In [30]:

# steps to standardize the data

#TO DO:  Insert code here
means = np.mean(data, axis=0)
std_devs = np.std(data, axis=0)
standardized_data = (data - means) / std_devs


In [31]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

### Step 2: Calculate the Covariance Matrix



In [32]:

# calculating the convariance matrix
covariance_matrix = np.cov(standardized_data, rowvar=False)
covariance_matrix

array([[ 1.2       , -0.42098785, -1.0835838 ,  0.90219291, -0.37000528],
       [-0.42098785,  1.2       ,  0.20397003, -0.77149364,  1.18751836],
       [-1.0835838 ,  0.20397003,  1.2       , -0.59947269,  0.22208218],
       [ 0.90219291, -0.77149364, -0.59947269,  1.2       , -0.70017993],
       [-0.37000528,  1.18751836,  0.22208218, -0.70017993,  1.2       ]])

### Step 3: Eigendecomposition on the Covariance Matrix


In [33]:



# Eigene values and eigen vectors

eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)


In [34]:
print(eigenvalues)

[3.80985761e+00 1.73655615e+00 4.94531029e-02 4.74189469e-05
 4.04085720e-01]


### Step 4: Sort the Principal Components
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

In [ ]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

order_of_importance = #TO DO: insert code here
print ( 'the order of importance is :\n {}'.format(order_of_importance))

# utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[#TO DO: insert code here]

print('\n\n sorted eigen values:\n{}'.format(sorted_eigenvalues))
sorted_eigenvectors = eigenvectors[#TO DO: insert code here] # sort the columns
print('\n\n The sorted eigen vector matrix is: \n {}'.format(sorted_eigenvectors))

the order of importance is :
 [0 1 2 3 4]


 sorted eigen values:
[8.93539590e+01 1.34853157e+01 1.60978112e+00 1.06316451e-01
 1.83336468e-04]


 The sorted eigen vector matrix is: 
 [[-0.05817655 -0.2631212   0.57237125  0.6292347  -0.45148374]
 [ 0.19774895 -0.03283879  0.06849106 -0.60720902 -0.7657827 ]
 [ 0.0328828   0.17887983 -0.75671562  0.45776292 -0.42983171]
 [-0.33200499 -0.88598416 -0.30234056 -0.11461168  0.01609676]
 [ 0.91989252 -0.33574235 -0.06059523  0.11259736  0.15724145]]


Question:

1. Why do we order eigen values and eigen vectors?

[Insert Answer here]

2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

[insert answer here]


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [ ]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

#TO DO: Insert code here
explained_variance = #TO DO: insert code here
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print( explained_variance)

['85.46%', '12.90%', '1.54%', '0.10%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [ ]:
k =  # select the number of principal components

reduced_data = #TO DO: Insert code here
reduced_data = np.matmul(#TO DO: insert code here)[#TO DO: insert code here] # transform the original data

In [ ]:
print(reduced_data)

[[ 1.07127878 -0.6983307 ]
 [-3.49014682 -0.59870297]
 [ 0.24003422 -0.48244534]
 [-0.14516166 -1.61189378]
 [ 1.34022572 -1.07434063]
 [-0.96573453 -2.23341502]]


In [ ]:
print(reduced_data.shape)

(6, 2)


# *What are 2 positive effects and 2 negative effects of PCA

Give 2 Benefits and 2 limitations


### Benefits

1. **Simplification through Dimensionality Reduction**: PCA streamlines the analysis by decreasing the number of features in a dataset. This leads to easier data handling, lower computational costs, and improved visualization of data.

2. **Enhanced Signal Clarity**: By concentrating on principal components that capture the most variance, PCA effectively filters out less significant, noisy elements in the data.

### Limitations

1. **Potential Loss of Data Variability**: When reducing dimensions, there is a risk of losing some variability in the data, which might cause the analysis to miss out on important details.

2. **Challenges in Interpretation**: The new features created by PCA are linear combinations of the original ones, making it harder to understand their direct relationship to real-world variables.
